const Data = [
  {
    Name: "Anastassia Stack",
    Role: "QA",
    email: "astack0@fotki.com",
    status: "Hold",
    form_status: "Incomplete",
  },
  {
    Name: "Darsie Trigwell",
    Role: "Fullstack",
    email: "dtrigwell1@examiner.com",
    status: "Joined",
    form_status: "Completed",
  },
  {
    Name: "Tyrus Rosander",
    Role: "Fullstack",
    email: "trosander2@example.com",
    status: "Joined",
    form_status: "Incomplete",
  },
  {
    Name: "Lillis Olford",
    Role: "Fullstack",
    email: "lolford3@ed.gov",
    status: "In Progress",
    form_status: "Completed",
  },
  {
    Name: "Kaela Tadman",
    Role: "Data Analyst",
    email: "ktadman4@scientificamerican.com",
    status: "Hold",
    form_status: "Completed",
  },
  {
    Name: "Inge Moscon",
    Role: "Devops",
    email: "imoscon5@hud.gov",
    status: "Joined",
    form_status: "Incomplete",
  },
  {
    Name: "Denyse Lehenmann",
    Role: "AI",
    email: "dlehenmann6@ted.com",
    status: "Joined",
    form_status: "Incomplete",
  },
  {
    Name: "Freedman Bohike",
    Role: "Fullstack",
    email: "fbohike7@disqus.com",
    status: "Joined",
    form_status: "Completed",
  },
  {
    Name: "Peta Pattullo",
    Role: "AI",
    email: "ppattullo8@webeden.co.uk",
    status: "Yet To Join",
    form_status: "Completed",
  },
  {
    Name: "Torr Yglesias",
    Role: "QA",
    email: "tyglesias9@soup.io",
    status: "Yet To Join",
    form_status: "Completed",
  },
  {
    Name: "Paulie Severns",
    Role: "AI",
    email: "psevernsa@elpais.com",
    status: "Pending",
    form_status: "Completed",
  },
  {
    Name: "Gloria Cape",
    Role: "Data Analyst",
    email: "gcapeb@livejournal.com",
    status: "Hold",
    form_status: "Incomplete",
  },
  {
    Name: "Pietro Chicotti",
    Role: "Data Analyst",
    email: "pchicottic@google.com.hk",
    status: "Joined",
    form_status: "Completed",
  },
  {
    Name: "Ellen Evison",
    Role: "Data Analyst",
    email: "eevisond@mysql.com",
    status: "Yet To Join",
    form_status: "Incomplete",
  },
  {
    Name: "Aida Alekseev",
    Role: "AI",
    email: "aalekseeve@earthlink.net",
    status: "Hold",
    form_status: "Incomplete",
  },
  {
    Name: "Brenna Gear",
    Role: "Fullstack",
    email: "bgearf@buzzfeed.com",
    status: "Hold",
    form_status: "Completed",
  },
  {
    Name: "Saul Le Guin",
    Role: "AI",
    email: "sleg@posterous.com",
    status: "Joined",
    form_status: "Completed",
  },
  {
    Name: "Orville Dimelow",
    Role: "Data Analyst",
    email: "odimelowh@ox.ac.uk",
    status: "Hold",
    form_status: "Completed",
  },
  {
    Name: "Loralyn Silverman",
    Role: "Devops",
    email: "lsilvermani@wp.com",
    status: "In Progress",
    form_status: "Incomplete",
  },
  {
    Name: "Roscoe Drew-Clifton",
    Role: "Data Analyst",
    email: "rdrewcliftonj@google.com.br",
    status: "Hold",
    form_status: "Completed",
  },
  {
    Name: "Kelley Blanpein",
    Role: "AI",
    email: "kblanpeink@pinterest.com",
    status: "Hold",
    form_status: "Incomplete",
  },
  {
    Name: "Jayme Doodney",
    Role: "Data Analyst",
    email: "jdoodneyl@tumblr.com",
    status: "In Progress",
    form_status: "Completed",
  },
  {
    Name: "Giles Colombier",
    Role: "AI",
    email: "gcolombierm@seattletimes.com",
    status: "Pending",
    form_status: "Incomplete",
  },
  {
    Name: "Ina Rambaut",
    Role: "AI",
    email: "irambautn@ehow.com",
    status: "Hold",
    form_status: "Completed",
  },
  {
    Name: "Wallas Sorel",
    Role: "QA",
    email: "wsorelo@gravatar.com",
    status: "Joined",
    form_status: "Completed",
  },
  {
    Name: "Chantal Kubelka",
    Role: "Data Analyst",
    email: "ckubelkap@forbes.com",
    status: "Yet To Join",
    form_status: "Incomplete",
  },
  {
    Name: "Wesley Bickardike",
    Role: "Data Analyst",
    email: "wbickardikeq@bbc.co.uk",
    status: "Pending",
    form_status: "Completed",
  },
  {
    Name: "Wake Fittes",
    Role: "Fullstack",
    email: "wfittesr@google.es",
    status: "In Progress",
    form_status: "Completed",
  },
  {
    Name: "Sanford Iuorio",
    Role: "Data Analyst",
    email: "siuorios@theguardian.com",
    status: "In Progress",
    form_status: "Completed",
  },
  {
    Name: "Boote Katzmann",
    Role: "Devops",
    email: "bkatzmannt@prlog.org",
    status: "Joined",
    form_status: "Incomplete",
  },
  {
    Name: "Darci Chavrin",
    Role: "Data Analyst",
    email: "dchavrinu@furl.net",
    status: "In Progress",
    form_status: "Completed",
  },
  {
    Name: "Jaimie Stickens",
    Role: "Devops",
    email: "jstickensv@usatoday.com",
    status: "In Progress",
    form_status: "Incomplete",
  },
  {
    Name: "Carolan Slessar",
    Role: "Data Analyst",
    email: "cslessarw@simplemachines.org",
    status: "Yet To Join",
    form_status: "Incomplete",
  },
  {
    Name: "Percy Driffield",
    Role: "Devops",
    email: "pdriffieldx@sohu.com",
    status: "Yet To Join",
    form_status: "Completed",
  },
  {
    Name: "Brigitta Tutchings",
    Role: "Data Analyst",
    email: "btutchingsy@indiegogo.com",
    status: "Joined",
    form_status: "Completed",
  },
  {
    Name: "Corrie Grahamslaw",
    Role: "Devops",
    email: "cgrahamslawz@techcrunch.com",
    status: "Joined",
    form_status: "Completed",
  },
  {
    Name: "Kylie Totaro",
    Role: "Data Analyst",
    email: "ktotaro10@yelp.com",
    status: "Pending",
    form_status: "Completed",
  },
  {
    Name: "Park Farley",
    Role: "Devops",
    email: "pfarley11@surveymonkey.com",
    status: "In Progress",
    form_status: "Completed",
  },
  {
    Name: "Coleman Banasiak",
    Role: "Devops",
    email: "cbanasiak12@sfgate.com",
    status: "Yet To Join",
    form_status: "Incomplete",
  },
  {
    Name: "Orel Verissimo",
    Role: "QA",
    email: "overissimo13@mozilla.org",
    status: "Hold",
    form_status: "Completed",
  },
];

export default Data;

export const techSkills = [
  "JavaScript",
  "Python",
  "Java",
  "HTML",
  "CSS",
  "SQL",
  "React",
  "Node.js",
  "Angular",
  "TypeScript",
  "Vue.js",
  "C++",
  "C#",
  "PHP",
  "Swift",
  "Ruby",
  "MongoDB",
  "Firebase",
  "Django",
  "ASP.NET",
  "Express.js",
  "Spring",
  "Redux",
  "TensorFlow",
  "Kubernetes",
  "Docker",
  "Git",
  "HTML5",
  "CSS3",
  "Sass",
  "Less",
  "Bootstrap",
  "Tailwind CSS",
  "jQuery",
  "RESTful API",
  "GraphQL",
  "PostgreSQL",
  "MySQL",
  "Microsoft Azure",
  "Amazon Web Services (AWS)",
  "Google Cloud Platform (GCP)",
  "Linux",
  "Unix",
  "Shell Scripting",
  "JSON",
  "XML",
  "Webpack",
  "Babel",
  "Jenkins",
  "Continuous Integration/Continuous Deployment (CI/CD)",
];
